spring:
  h2:
    port: 8081
    console:
      enabled: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: "url: jdbc:h2:file:~/xml"
    username: user
    password: 123
    driver-class-name: org.h2.Driver
    schema: classpath:schema.sql
  activemq:
    queue: order-queue
    sender-name: xml-service
    receiver-name: xml-receiver
    broker-url: vm://embedded?broker.persistent=false,useShutdownHook=false
    in-memory: true
    non-blocking-redelivery: true

  directories:
    start-input: /tmp/input
    output: /tmp/output
    archive: /tmp/archive