spring:
  h2:
    console:
      enabled: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: "jdbc:h2:tcp://localhost:8081/mem:xml"
    username: user
    password: 123
    driver-class-name: org.h2.Driver

